#!/usr/bin/env bash 
# this script will display username. user ID , and home directory from /etc/passwrd
while read -r line 
do
	username=$(echo "$line" | cut -d: -f1)
	userid=$(echo "$line" | cut -d: -f3)
	homedir=$(echo "$line" | cut -d: -f6)
	echo "$username:$userid:$homedir"
done < /etc/passwd
