#!/usr/bin/env bash
#this script will creat PID file and will display messages bades on signals 
echo $$ > /var/run/myscript.pid

cleanup() {
	rm -f /var/run/myscript.pid
	exit 0
}
trap "echo 'The kill command wont stop me!'; cleanup" SIGTERM
trap "echo 'ouch! That Ctrl+c hurts!'" SIGINT
trap cleanup SIGQUIT

while true
do 
	echo "Running forever and ever!"
	sleep 2
done
